import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from "../components/Hero";
import Second from "../components/Second";
import ReasonsForBis from "../components/ReasonsForBis";
import ReasonsForAuth from "../components/ReasonsForAuth";
import Contacts from "../components/Contacts";
import sample from "../public/Waves7.mp4"
import Navbar from "../components/Navbar";
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-white">
          <video className='videoTag' autoPlay loop muted>
              <source src={sample} type='video/mp4' />
          </video>
          <Navbar/>
        <Hero />
        <Second/>
          <ReasonsForBis/>
          <ReasonsForAuth/>
          <Contacts/>
     </div>
    </div>
  )
}
